In [1]:
import pandas as pd

IMPORTAR TABELA

In [2]:
df = pd.read_csv('empresa8.CSV', encoding='LATIN-1', sep=';')
df

,32066830,PASTELLO PASTELARIA GOURMET LTDA,2062,49,"5000,00",01,Unnamed: 6
0,32066831,PARTIDO REPUBLICANO DA ORDEM SOCIAL - PACATUBA...,3271,16,"0,00",5.0,NaN
1,32066832,JOSE ALIPIO GARCIA GOUVEA - ESPORTES,2135,50,"10000,00",1.0,NaN
2,32066833,M&M COMERCIO DE PRODUTOS AGROPECUARIOS LTDA,2062,49,"10000,00",3.0,NaN
3,32066834,ISAIAS RODRIGUES 12415932809,2135,50,"5000,00",1.0,NaN
4,32066835,JOSE DENNES DOS SANTOS SILVA,2135,50,"1000,00",1.0,NaN
...,...,...,...,...,...,...,...
4494854,36627970,GILVANDERSON SANTOS DA SILVA 45301862880,2135,50,"100,00",1.0,NaN
4494855,36627971,JONATHAS AUGUSTO DOS SANTOS CAMILO 40993054811,2135,50,"3000,00",1.0,NaN
4494856,36627972,ANGELINA ANTUNES DA LUZ BORGES 87429187900,2135,50,"1000,00",1.0,NaN
4494857,36627973,ANTONIO PEREIRA ARANTES NETO 01699985170,2135,50,"1000,00",1.0,NaN
4494858,36627975,MICHELI PINHEIRO FLOR 06035748902,2135,50,"1000,00",1.0,NaN

ELIMINAR HEAD

In [3]:
df = pd.read_csv('empresa8.CSV', encoding='LATIN-1', sep=';', header=None)
df

,0,1,2,3,4,5,6
0,32066830,PASTELLO PASTELARIA GOURMET LTDA,2062,49,"5000,00",1.0,NaN
1,32066831,PARTIDO REPUBLICANO DA ORDEM SOCIAL - PACATUBA...,3271,16,"0,00",5.0,NaN
2,32066832,JOSE ALIPIO GARCIA GOUVEA - ESPORTES,2135,50,"10000,00",1.0,NaN
3,32066833,M&M COMERCIO DE PRODUTOS AGROPECUARIOS LTDA,2062,49,"10000,00",3.0,NaN
4,32066834,ISAIAS RODRIGUES 12415932809,2135,50,"5000,00",1.0,NaN
...,...,...,...,...,...,...,...
4494855,36627970,GILVANDERSON SANTOS DA SILVA 45301862880,2135,50,"100,00",1.0,NaN
4494856,36627971,JONATHAS AUGUSTO DOS SANTOS CAMILO 40993054811,2135,50,"3000,00",1.0,NaN
4494857,36627972,ANGELINA ANTUNES DA LUZ BORGES 87429187900,2135,50,"1000,00",1.0,NaN
4494858,36627973,ANTONIO PEREIRA ARANTES NETO 01699985170,2135,50,"1000,00",1.0,NaN
4494859,36627975,MICHELI PINHEIRO FLOR 06035748902,2135,50,"1000,00",1.0,NaN

INSERIR HEAD

In [4]:
df.columns = ['CNPJ', 'INDEFICADOR MATRIZ/FILIAL', 'RAZÃO SOCIAL', 'NOME FANTASIA', 'SITUAÇÃO CADASTRAL',
                    'DATA SITUAÇÃO CADASTRAL', 'CO-PAÍS']
df

,CNPJ,INDEFICADOR MATRIZ/FILIAL,RAZÃO SOCIAL,NOME FANTASIA,SITUAÇÃO CADASTRAL,DATA SITUAÇÃO CADASTRAL,CO-PAÍS
0,32066830,PASTELLO PASTELARIA GOURMET LTDA,2062,49,"5000,00",1.0,NaN
1,32066831,PARTIDO REPUBLICANO DA ORDEM SOCIAL - PACATUBA...,3271,16,"0,00",5.0,NaN
2,32066832,JOSE ALIPIO GARCIA GOUVEA - ESPORTES,2135,50,"10000,00",1.0,NaN
3,32066833,M&M COMERCIO DE PRODUTOS AGROPECUARIOS LTDA,2062,49,"10000,00",3.0,NaN
4,32066834,ISAIAS RODRIGUES 12415932809,2135,50,"5000,00",1.0,NaN
...,...,...,...,...,...,...,...
4494855,36627970,GILVANDERSON SANTOS DA SILVA 45301862880,2135,50,"100,00",1.0,NaN
4494856,36627971,JONATHAS AUGUSTO DOS SANTOS CAMILO 40993054811,2135,50,"3000,00",1.0,NaN
4494857,36627972,ANGELINA ANTUNES DA LUZ BORGES 87429187900,2135,50,"1000,00",1.0,NaN
4494858,36627973,ANTONIO PEREIRA ARANTES NETO 01699985170,2135,50,"1000,00",1.0,NaN
4494859,36627975,MICHELI PINHEIRO FLOR 06035748902,2135,50,"1000,00",1.0,NaN

ELIMINAR A ÚLTIMA LINHA

In [5]:
df.drop(df.tail(1).index, inplace=True)
df

,CNPJ,INDEFICADOR MATRIZ/FILIAL,RAZÃO SOCIAL,NOME FANTASIA,SITUAÇÃO CADASTRAL,DATA SITUAÇÃO CADASTRAL,CO-PAÍS
0,32066830,PASTELLO PASTELARIA GOURMET LTDA,2062,49,"5000,00",1.0,NaN
1,32066831,PARTIDO REPUBLICANO DA ORDEM SOCIAL - PACATUBA...,3271,16,"0,00",5.0,NaN
2,32066832,JOSE ALIPIO GARCIA GOUVEA - ESPORTES,2135,50,"10000,00",1.0,NaN
3,32066833,M&M COMERCIO DE PRODUTOS AGROPECUARIOS LTDA,2062,49,"10000,00",3.0,NaN
4,32066834,ISAIAS RODRIGUES 12415932809,2135,50,"5000,00",1.0,NaN
...,...,...,...,...,...,...,...
4494854,36627969,VINICIUS ESMERELI 23381366831,2135,50,"2000,00",1.0,NaN
4494855,36627970,GILVANDERSON SANTOS DA SILVA 45301862880,2135,50,"100,00",1.0,NaN
4494856,36627971,JONATHAS AUGUSTO DOS SANTOS CAMILO 40993054811,2135,50,"3000,00",1.0,NaN
4494857,36627972,ANGELINA ANTUNES DA LUZ BORGES 87429187900,2135,50,"1000,00",1.0,NaN
4494858,36627973,ANTONIO PEREIRA ARANTES NETO 01699985170,2135,50,"1000,00",1.0,NaN

EXPORTAR TABELA:

In [6]:
df.to_csv('n_empresa8.csv', index=False)
df

,CNPJ,INDEFICADOR MATRIZ/FILIAL,RAZÃO SOCIAL,NOME FANTASIA,SITUAÇÃO CADASTRAL,DATA SITUAÇÃO CADASTRAL,CO-PAÍS
0,32066830,PASTELLO PASTELARIA GOURMET LTDA,2062,49,"5000,00",1.0,NaN
1,32066831,PARTIDO REPUBLICANO DA ORDEM SOCIAL - PACATUBA...,3271,16,"0,00",5.0,NaN
2,32066832,JOSE ALIPIO GARCIA GOUVEA - ESPORTES,2135,50,"10000,00",1.0,NaN
3,32066833,M&M COMERCIO DE PRODUTOS AGROPECUARIOS LTDA,2062,49,"10000,00",3.0,NaN
4,32066834,ISAIAS RODRIGUES 12415932809,2135,50,"5000,00",1.0,NaN
...,...,...,...,...,...,...,...
4494854,36627969,VINICIUS ESMERELI 23381366831,2135,50,"2000,00",1.0,NaN
4494855,36627970,GILVANDERSON SANTOS DA SILVA 45301862880,2135,50,"100,00",1.0,NaN
4494856,36627971,JONATHAS AUGUSTO DOS SANTOS CAMILO 40993054811,2135,50,"3000,00",1.0,NaN
4494857,36627972,ANGELINA ANTUNES DA LUZ BORGES 87429187900,2135,50,"1000,00",1.0,NaN
4494858,36627973,ANTONIO PEREIRA ARANTES NETO 01699985170,2135,50,"1000,00",1.0,NaN