In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('estabelecimento3.csv', encoding = 'latin1', sep = ';')
df

C:\Users\Edson\AppData\Local\Temp\ipykernel_9068\565687779.py:1: DtypeWarning: Columns (8,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('estabelecimento3.csv', encoding = 'latin1', sep = ';')

,27364560,0001,81,1,Unnamed: 4,08,20221219,01,Unnamed: 8,Unnamed: 9,...,7107,11,21659600,11.1,21659601,Unnamed: 25,Unnamed: 26,SERGIO.CAPPELLINI@PCA.COM.BR,Unnamed: 28,Unnamed: 29
0,20101604,2,12,2,NaN,8,20180222,1,NaN,NaN,...,6425,16.0,37214671.0,NaN,NaN,NaN,NaN,SERGIOBONAMIM@GMAIL.COM,NaN,NaN
1,27364588,1,19,1,NaN,4,20210422,63,NaN,NaN,...,3661,73.0,35250001.0,NaN,NaN,NaN,NaN,rildonunes2016@hotmail.com,NaN,NaN
2,27364600,1,95,1,NaN,8,20221103,1,NaN,NaN,...,8705,55.0,91043738.0,NaN,NaN,NaN,NaN,SPARREMBERGERD@GMAIL.COM,NaN,NaN
3,27364613,1,64,1,NaN,8,20211021,1,NaN,NaN,...,2571,83.0,96172438.0,NaN,NaN,NaN,NaN,DANIEL-SIQUEIRA90@HOTMAIL.COM,NaN,NaN
4,27364626,1,33,1,BEL TERAPIA HOLISTICA,8,20230328,75,NaN,NaN,...,7107,11.0,82893215.0,NaN,NaN,NaN,NaN,BELCERIBELLI@HOTMAIL.COM,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753429,15265563,1,89,1,NaN,8,20180201,67,NaN,NaN,...,4481,31.0,87733438.0,NaN,NaN,NaN,NaN,lucontagem26@hotmail.com,NaN,NaN
4753430,15266288,1,18,1,NaN,2,20120326,0,NaN,NaN,...,7107,11.0,59243850.0,NaN,NaN,NaN,NaN,SON.AI@HOTMAIL.COM,NaN,NaN
4753431,15266303,1,28,1,NaN,8,20180201,67,NaN,NaN,...,4123,31.0,35822027.0,NaN,NaN,NaN,NaN,mejvilar@gmail.com,NaN,NaN
4753432,15266318,1,96,1,RESTAURANTE RECANTO DO SABOR,8,20130227,1,NaN,NaN,...,2051,83.0,88316614.0,NaN,NaN,NaN,NaN,JUNIORCLAUDINOADM@HOTMAIL.COM,NaN,NaN
4753433,15266336,1,78,1,NaN,8,20231028,1,NaN,NaN,...,6477,11.0,34357826.0,NaN,NaN,NaN,NaN,niccalcados@gmail.com,NaN,NaN

In [5]:
df = pd.read_csv('estabelecimento3.csv', encoding = 'latin1', sep = ';', header=None)
df

C:\Users\Edson\AppData\Local\Temp\ipykernel_9068\610598172.py:1: DtypeWarning: Columns (8,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('estabelecimento3.csv', encoding = 'latin1', sep = ';', header=None)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,27364560,1,81,1,NaN,8,20221219,1,NaN,NaN,...,7107,11.0,21659600.0,11.0,21659601.0,NaN,NaN,SERGIO.CAPPELLINI@PCA.COM.BR,NaN,NaN
1,20101604,2,12,2,NaN,8,20180222,1,NaN,NaN,...,6425,16.0,37214671.0,NaN,NaN,NaN,NaN,SERGIOBONAMIM@GMAIL.COM,NaN,NaN
2,27364588,1,19,1,NaN,4,20210422,63,NaN,NaN,...,3661,73.0,35250001.0,NaN,NaN,NaN,NaN,rildonunes2016@hotmail.com,NaN,NaN
3,27364600,1,95,1,NaN,8,20221103,1,NaN,NaN,...,8705,55.0,91043738.0,NaN,NaN,NaN,NaN,SPARREMBERGERD@GMAIL.COM,NaN,NaN
4,27364613,1,64,1,NaN,8,20211021,1,NaN,NaN,...,2571,83.0,96172438.0,NaN,NaN,NaN,NaN,DANIEL-SIQUEIRA90@HOTMAIL.COM,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753430,15265563,1,89,1,NaN,8,20180201,67,NaN,NaN,...,4481,31.0,87733438.0,NaN,NaN,NaN,NaN,lucontagem26@hotmail.com,NaN,NaN
4753431,15266288,1,18,1,NaN,2,20120326,0,NaN,NaN,...,7107,11.0,59243850.0,NaN,NaN,NaN,NaN,SON.AI@HOTMAIL.COM,NaN,NaN
4753432,15266303,1,28,1,NaN,8,20180201,67,NaN,NaN,...,4123,31.0,35822027.0,NaN,NaN,NaN,NaN,mejvilar@gmail.com,NaN,NaN
4753433,15266318,1,96,1,RESTAURANTE RECANTO DO SABOR,8,20130227,1,NaN,NaN,...,2051,83.0,88316614.0,NaN,NaN,NaN,NaN,JUNIORCLAUDINOADM@HOTMAIL.COM,NaN,NaN
4753434,15266336,1,78,1,NaN,8,20231028,1,NaN,NaN,...,6477,11.0,34357826.0,NaN,NaN,NaN,NaN,niccalcados@gmail.com,NaN,NaN

In [6]:
df.columns = ['DESCRIÇÃO TIPO LOGRADOURO', 'LOGRADOURO', 'NUMERO', 'COMPLEMENTO', 'BAIRRO', 'CEP',
                'UF', 'CODIGO MUNICIPIO', 'MUNICIPIO', 'DDD-TELEFONE-1', 'DDD', 'TELEFONE-1', 'DDD-TELEFONE-2',
                'DDD-2', 'TELEFONE-2', 'DDD-FAX', 'NU-DDD-FAX', 'NU-FAX', 'CORREIO ELETRONICO', 
                'QUALIFICAÇÃO DO RESPONSÁVEL', 'CAPITAL SOCIAL DA EMPRESA', 'PORTE-EMPRESA', 'OPÇÃO PELO SIMPLES',
                'DATA OPCAO PELO SIMPLES', 'DATA EXCLUSÃO DO SIMPLES', 'OPÇÃO PELO MEI', 'SITUAÇÃO ESPECIAL',
                'DATA SITUAÇÃO ESPECIAL', 'FILLER', 'FIM DE REGISTRO']
df

,DESCRIÇÃO TIPO LOGRADOURO,LOGRADOURO,NUMERO,COMPLEMENTO,BAIRRO,CEP,UF,CODIGO MUNICIPIO,MUNICIPIO,DDD-TELEFONE-1,...,CAPITAL SOCIAL DA EMPRESA,PORTE-EMPRESA,OPÇÃO PELO SIMPLES,DATA OPCAO PELO SIMPLES,DATA EXCLUSÃO DO SIMPLES,OPÇÃO PELO MEI,SITUAÇÃO ESPECIAL,DATA SITUAÇÃO ESPECIAL,FILLER,FIM DE REGISTRO
0,27364560,1,81,1,NaN,8,20221219,1,NaN,NaN,...,7107,11.0,21659600.0,11.0,21659601.0,NaN,NaN,SERGIO.CAPPELLINI@PCA.COM.BR,NaN,NaN
1,20101604,2,12,2,NaN,8,20180222,1,NaN,NaN,...,6425,16.0,37214671.0,NaN,NaN,NaN,NaN,SERGIOBONAMIM@GMAIL.COM,NaN,NaN
2,27364588,1,19,1,NaN,4,20210422,63,NaN,NaN,...,3661,73.0,35250001.0,NaN,NaN,NaN,NaN,rildonunes2016@hotmail.com,NaN,NaN
3,27364600,1,95,1,NaN,8,20221103,1,NaN,NaN,...,8705,55.0,91043738.0,NaN,NaN,NaN,NaN,SPARREMBERGERD@GMAIL.COM,NaN,NaN
4,27364613,1,64,1,NaN,8,20211021,1,NaN,NaN,...,2571,83.0,96172438.0,NaN,NaN,NaN,NaN,DANIEL-SIQUEIRA90@HOTMAIL.COM,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753430,15265563,1,89,1,NaN,8,20180201,67,NaN,NaN,...,4481,31.0,87733438.0,NaN,NaN,NaN,NaN,lucontagem26@hotmail.com,NaN,NaN
4753431,15266288,1,18,1,NaN,2,20120326,0,NaN,NaN,...,7107,11.0,59243850.0,NaN,NaN,NaN,NaN,SON.AI@HOTMAIL.COM,NaN,NaN
4753432,15266303,1,28,1,NaN,8,20180201,67,NaN,NaN,...,4123,31.0,35822027.0,NaN,NaN,NaN,NaN,mejvilar@gmail.com,NaN,NaN
4753433,15266318,1,96,1,RESTAURANTE RECANTO DO SABOR,8,20130227,1,NaN,NaN,...,2051,83.0,88316614.0,NaN,NaN,NaN,NaN,JUNIORCLAUDINOADM@HOTMAIL.COM,NaN,NaN
4753434,15266336,1,78,1,NaN,8,20231028,1,NaN,NaN,...,6477,11.0,34357826.0,NaN,NaN,NaN,NaN,niccalcados@gmail.com,NaN,NaN

In [7]:
df.drop(df.tail(1).index, inplace=True)
df

,DESCRIÇÃO TIPO LOGRADOURO,LOGRADOURO,NUMERO,COMPLEMENTO,BAIRRO,CEP,UF,CODIGO MUNICIPIO,MUNICIPIO,DDD-TELEFONE-1,...,CAPITAL SOCIAL DA EMPRESA,PORTE-EMPRESA,OPÇÃO PELO SIMPLES,DATA OPCAO PELO SIMPLES,DATA EXCLUSÃO DO SIMPLES,OPÇÃO PELO MEI,SITUAÇÃO ESPECIAL,DATA SITUAÇÃO ESPECIAL,FILLER,FIM DE REGISTRO
0,27364560,1,81,1,NaN,8,20221219,1,NaN,NaN,...,7107,11.0,21659600.0,11.0,21659601.0,NaN,NaN,SERGIO.CAPPELLINI@PCA.COM.BR,NaN,NaN
1,20101604,2,12,2,NaN,8,20180222,1,NaN,NaN,...,6425,16.0,37214671.0,NaN,NaN,NaN,NaN,SERGIOBONAMIM@GMAIL.COM,NaN,NaN
2,27364588,1,19,1,NaN,4,20210422,63,NaN,NaN,...,3661,73.0,35250001.0,NaN,NaN,NaN,NaN,rildonunes2016@hotmail.com,NaN,NaN
3,27364600,1,95,1,NaN,8,20221103,1,NaN,NaN,...,8705,55.0,91043738.0,NaN,NaN,NaN,NaN,SPARREMBERGERD@GMAIL.COM,NaN,NaN
4,27364613,1,64,1,NaN,8,20211021,1,NaN,NaN,...,2571,83.0,96172438.0,NaN,NaN,NaN,NaN,DANIEL-SIQUEIRA90@HOTMAIL.COM,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753429,15266249,1,10,1,NaN,3,20211009,74,NaN,573.0,...,9707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4753430,15265563,1,89,1,NaN,8,20180201,67,NaN,NaN,...,4481,31.0,87733438.0,NaN,NaN,NaN,NaN,lucontagem26@hotmail.com,NaN,NaN
4753431,15266288,1,18,1,NaN,2,20120326,0,NaN,NaN,...,7107,11.0,59243850.0,NaN,NaN,NaN,NaN,SON.AI@HOTMAIL.COM,NaN,NaN
4753432,15266303,1,28,1,NaN,8,20180201,67,NaN,NaN,...,4123,31.0,35822027.0,NaN,NaN,NaN,NaN,mejvilar@gmail.com,NaN,NaN
4753433,15266318,1,96,1,RESTAURANTE RECANTO DO SABOR,8,20130227,1,NaN,NaN,...,2051,83.0,88316614.0,NaN,NaN,NaN,NaN,JUNIORCLAUDINOADM@HOTMAIL.COM,NaN,NaN

In [8]:
df.to_csv('n_estabelecimento3.csv', index=False)
df

,DESCRIÇÃO TIPO LOGRADOURO,LOGRADOURO,NUMERO,COMPLEMENTO,BAIRRO,CEP,UF,CODIGO MUNICIPIO,MUNICIPIO,DDD-TELEFONE-1,...,CAPITAL SOCIAL DA EMPRESA,PORTE-EMPRESA,OPÇÃO PELO SIMPLES,DATA OPCAO PELO SIMPLES,DATA EXCLUSÃO DO SIMPLES,OPÇÃO PELO MEI,SITUAÇÃO ESPECIAL,DATA SITUAÇÃO ESPECIAL,FILLER,FIM DE REGISTRO
0,27364560,1,81,1,NaN,8,20221219,1,NaN,NaN,...,7107,11.0,21659600.0,11.0,21659601.0,NaN,NaN,SERGIO.CAPPELLINI@PCA.COM.BR,NaN,NaN
1,20101604,2,12,2,NaN,8,20180222,1,NaN,NaN,...,6425,16.0,37214671.0,NaN,NaN,NaN,NaN,SERGIOBONAMIM@GMAIL.COM,NaN,NaN
2,27364588,1,19,1,NaN,4,20210422,63,NaN,NaN,...,3661,73.0,35250001.0,NaN,NaN,NaN,NaN,rildonunes2016@hotmail.com,NaN,NaN
3,27364600,1,95,1,NaN,8,20221103,1,NaN,NaN,...,8705,55.0,91043738.0,NaN,NaN,NaN,NaN,SPARREMBERGERD@GMAIL.COM,NaN,NaN
4,27364613,1,64,1,NaN,8,20211021,1,NaN,NaN,...,2571,83.0,96172438.0,NaN,NaN,NaN,NaN,DANIEL-SIQUEIRA90@HOTMAIL.COM,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753429,15266249,1,10,1,NaN,3,20211009,74,NaN,573.0,...,9707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4753430,15265563,1,89,1,NaN,8,20180201,67,NaN,NaN,...,4481,31.0,87733438.0,NaN,NaN,NaN,NaN,lucontagem26@hotmail.com,NaN,NaN
4753431,15266288,1,18,1,NaN,2,20120326,0,NaN,NaN,...,7107,11.0,59243850.0,NaN,NaN,NaN,NaN,SON.AI@HOTMAIL.COM,NaN,NaN
4753432,15266303,1,28,1,NaN,8,20180201,67,NaN,NaN,...,4123,31.0,35822027.0,NaN,NaN,NaN,NaN,mejvilar@gmail.com,NaN,NaN
4753433,15266318,1,96,1,RESTAURANTE RECANTO DO SABOR,8,20130227,1,NaN,NaN,...,2051,83.0,88316614.0,NaN,NaN,NaN,NaN,JUNIORCLAUDINOADM@HOTMAIL.COM,NaN,NaN